### ISSUE TITLE
Method BFGS cannot handle constraints nor bounds.   RuntimeWarning issue with certain input files

### ISSUE THREAD

**Issue by damblef** [stevenliuyi/admix#1]
Hi, 

I have stumbled upon an issue with some FTDNA and Ancestry files.  Whatever the model used, the calculator returns the following error:

`/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/_minimize.py:324: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)
`
In addition, the percentage returned is the same for each reference population.  

Note this is on OSX and the input files do not appear to be out of the ordinary.

Has anyone experienced a similar issue and been found a solution?  I have to admit that I am rather ignorant when it comes to scipy and numpy.

Many thanks for your help.

**Comment by stevenliuyi** [comment]
Hi, I'm not sure what caused the problem, but if you can send me a file which you have the problem with, I can look into it for you.

**Comment by stevenliuyi** [comment]
Hi @damblef , thanks for your previous emails. You were right that the issue was due to the file format change, and I've fixed the issue in the newest release. Thank you for your contribution!
