### ISSUE TITLE
My own reference populations

### ISSUE THREAD

**Issue by herroannekim** [stevenliuyi/admix#2]
How do I use this repo to make an admixture calculation with my own reference populations?  Thanks!

**Comment by stevenliuyi** [comment]
Hi @herroannekim , I'm very sorry for the late reply. You can put your data (*.alleles and *.F file) in the `data` folder, and then add the corresponding information to `admix_models.py`, specifically the `models` function and the `populations` function. Hope it helps!

**Comment by herroannekim** [comment]
Hi Yi,

Thanks!  That's helpful for future projects :)

All the Best,
Anne Kim
